run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-files:
    - ".*\\.my\\.go$"
    - lib/bad.go
  modules-download-mode: readonly
  allow-parallel-runners: false
  go: '1.19'

output:
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  path-prefix: ""
  sort-results: true
